# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [(modulesPath + "/installer/scan/not-detected.nix")];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod"];
  boot.kernelModules = ["kvm-intel"];
  boot.initrd.kernelModules = [];
  boot.extraModulePackages = [];

  fileSystems = {
    #"/" = {
    #  device = "none";
    #  fsType = "tmpfs";
    #  neededForBoot = true;
    #  options = ["defaults" "size=40%" "mode=755"];
    #};

    "/" = {
      device = "/dev/disk/by-uuid/7335d48f-7978-4bf3-aeda-de1fb500ca99";
      fsType = "ext4";
      neededForBoot = true;
    };

    "/boot/efi" = {
      device = "/dev/disk/by-uuid/5288-1A02";
      fsType = "vfat";
      neededForBoot = true;
      options = ["fmask=0137" "dmask=0027"];
    };
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  #networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
